### ISSUE TITLE
Cambiar diseño

### ISSUE THREAD

**Issue by mgmacias95** [geekandtechgirls/geekandtechgirls.github.io#14]
El actual diseño carga todos los elementos de la página a la vez, esto incluye todas las fotos y texto de todas las entradas de la página. Esto hace que el tamaño de la misma sea demasiado grande y que cargue demasiado lento. Esto hace que perdamos lectores, ya que el éxito de una web depende de la experiencia de sus usuarios.

Por ello, creo que debemos hacer un nuevo diseño que evite estos problemas.

https://tools.pingdom.com/#!/eAoZ5C/https://geekandtechgirls.github.io/

Vamos a contar con la ayuda de @erseco

**Comment by erseco** [comment]
Encantado de poder ayudar. Yo creo que el diseño está bien, solo falta optimizar detalles para reducir el peso de la página.

**Comment by yabirgb** [comment]
Yo intentaría reducir el tamaño de las imágenes de algún modo y juntar algunos js que aunque son pequeños gasta tiempo en llamar a cada uno

**Comment by mgmacias95** [comment]
@yabirgb las imágnes he intentado reducirlas lo máximo que he podido, actualemten todas tienen aproximadametne 1000x666 de tamaño. Creo que si las reduzco más voy a perder mucha calidad. En cuanto a juntar los .js sí que es algo que podría hacer 👍 !! muchas gracias ;D

**Comment by erseco** [comment]
Lo ideal en estos casos es tener dos conjuntos de imagenes, las grandes propiamente dichas y una carpeta con los "thumbnails" que tengan un tamaño de por ejemplo 400x300, esto reduciría enormemente la carga de la web, se podría automatizar la creación de los thumbnails con un script bash que use imagemagick
