### ISSUE TITLE
Añadir anuncios de eventos

### ISSUE THREAD

**Issue by unintendedbear** [geekandtechgirls/geekandtechgirls.github.io#2]
¿Se puede sincronizar con meetup? O hacer algo similar.

**Comment by unintendedbear** [comment]
Parece que no se pueden exportar los eventos peeeeeeeeeeeero sí podemos hacer un script que haga scrapping de los eventos en la propia página, formatear la info y ponerla en la web.

**Comment by mgmacias95** [comment]
sí, eso me parece guay :D, de hecho creo que lo de hacer scrapping y luego formatear con un script lo he dicho por el slack XD

**Comment by unintendedbear** [comment]
Guay, pues me lo asigno que tengo ganas de programar algo xD
Es que sólo se puede exportar a cosas en plan google calendar u Outlook T_T
