### ISSUE TITLE
Crear sección para los eventos

### ISSUE THREAD

**Issue by unintendedbear** [geekandtechgirls/geekandtechgirls.github.io#5]
Que incluirá enlaces a los eventos de meetup creados con el script hecho en #2

**Comment by mgmacias95** [comment]
he encontrado en stackoverflow cómo hacerlo: http://stackoverflow.com/questions/27583597/categories-in-jekyll
es simplemente añadiendo una categoría al blog :D

**Comment by unintendedbear** [comment]
Genial! lo hago ahora mismo :)
Muchas gracias! :dancing_women:
